
name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flet
        run: |
          pip install flet

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk

      - name: Build APK
        run: |
          flet build android

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: ./build/app-debug.apk
